flashcards:
  new_learnt_words: 1
  progress_id: "progress_bar"
  bar_class: ""
  pbar_class: ""
  panel_id: "panel"
  result_id: "result"
  write_id: "write"
writes:
  size: 0
  remain:
    bar_class: ""
    pbar_class: ""
    id: "remain_bar"
  correct:
    bar_class: "soft-green"
    pbar_class: "green"
    id: "correct_bar"
  incorrect:
    bar_class: "soft-red"
    pbar_class: "red"
    id: "incorrect_bar"
users:
  temp_id: 0
number_of_feed_noti: 5
recent_topics: 3
