flashcards:
  new_learnt_words: 1
  progress_id: "progress_bar"
  progress_class: ""
writes:
  size: 0
  remain:
    css_class: ""
    id: "remain_bar"
  correct:
    css_class: "green"
    id: "correct_bar"
  incorrect:
    css_class: "red"
    id: "incorrect_bar"
